db:
    # Enable/disable the automatic migrations feature
    automigrate: true
    # Database name
    dbname: name
    # Database host
    host: localhost
    # Path to migrations directory
    migrations-path: db/migrations
    # Database password (also allowed via PG_PASSWORD env)
    password: ""
    # Database port
    port: "5432"
    # Database sslmode
    sslmode: disable
    # Database user (also allowed via PG_USER env)
    user: ""
eth:
    client:
        # HTTP endpoint of JSON-RPC enabled Ethereum node
        http: ""
        # Interval to be used for polling the Ethereum node for best block
        poll-interval: 15s
        # WS endpoint of JSON-RPC enabled Ethereum node (provide this only if you want to use websocket subscription for tracking best block)
        ws: ""
    # Maximum JSON-RPC requests to batch together
    max-batch: 100
ethtypes:
    # Folder containing ABI JSONs
    abi-folder: ethtypes/_source
    # Path where to generate packages. Final folder represents package name
    package-path: ethtypes
feature:
    contract-state:
        # Enable/disable state scraping (if enabled, it requires archive node support)
        enabled: true
    integrity:
        # Enable/disable the integrity checker
        enabled: true
    queuekeeper:
        # Enable/disable the queue keeper (watch new heads and store into the queue)
        enabled: true
        # The amount of blocks to lag behind the tip of the chain
        lag: 10
    # Enable this if the scraper should replace existing blocks instead of skipping them
    replace-blocks: false
    # Enable this if the scraper should retry failed blocks instead of skipping them. If false, disable integrity checker.
    requeue-failed-blocks: true
# Display debug messages
logging: '*=info'
metrics:
    # Port on which to serve Prometheus metrics
    port: 9909
redis:
    # The name of the list to be used for task management
    list: todo
    # Redis password
    password: ""
    # Redis server URL
    server: localhost:6379
storable:
    accounterc20transfers:
        enabled: true
    barn:
        # Address of barn staking contract
        address: ""
        # Enable/disable barn scraping
        enabled: true
        # Enable/disable barn notifications
        notifications: true
    erc20transfers:
        enabled: true
    governance:
        # Address of governance contract
        address: ""
        # Enable/disable governance scraping
        enabled: true
        # Enable/disable governance notifications
        notifications: true
    smartalpha:
        enabled: true
    smartexposure:
        enabled: true
        epoolhelperaddress: ""
        epoolperipheryaddress: ""
        etokenfactoryaddress: ""
    smartyield:
        enabled: true
        notifications: true
        rewards:
            factories: ""
    tokenprices:
        enabled: true
    yieldfarming:
        address: ""
        enabled: true
syncer:
    # The datasets to sync
    datasets: []
    # The network to sync
    network: ""
    # Path to sync files folder
    path: ""
