api:
    # Enable development cors for HTTP API
    dev-cors: false
    # Allowed host for HTTP API dev cors
    dev-cors-host: ""
    # HTTP API port
    port: "3001"
db:
    # Enable/disable the automatic migrations feature
    automigrate: true
    # Database name
    dbname: name
    # Database host
    host: localhost
    # Database password (also allowed via PG_PASSWORD env)
    password: ""
    # Database port
    port: "5432"
    # Database sslmode
    sslmode: disable
    # Database user (also allowed via PG_USER env)
    user: ""
eth:
    client:
        # HTTP endpoint of JSON-RPC enabled Ethereum node
        http: ""
        # Interval to be used for polling the Ethereum node for best block
        poll-interval: 15s
        # WS endpoint of JSON-RPC enabled Ethereum node (provide this only if you want to use websocket subscription for tracking best block)
        ws: ""
feature:
    integrity:
        # Enable/disable the integrity checker
        enabled: true
    queuekeeper:
        # Enable/disable the queue keeper (watch new heads and store into the queue)
        enabled: true
        # The amount of blocks to lag behind the tip of the chain
        lag: 10
    # Enable this if the scraper should replace existing blocks instead of skipping them
    replace-blocks: false
# Display debug messages
logging: '*=info'
accountERC20Transfers:
    enabled: true
redis:
    # The name of the list to be used for task management
    list: todo
    # Redis password
    password: ""
    # Redis server URL
    server: localhost:6379

