# database fields
db:
  # Database host
  host: "meminero-postgres"

  # Database port
  port: 5432

  # Database sslmode
  sslmode: "disable"

  # Database name
  dbname: "barnbridge"

  # Database user (also allowed via PG_USER env var)
  user: "barnbridge"

  password: "password"

  automigrate: true

  migrations-path: db/migrations

# ethereum-related fields
eth:
  client:
    # HTTP endpoint of a web3-compatible node (mandatory)
    http: "http://localhost:8545"

    # Websockets endpoint of JSON-RPC enabled node (optional)
    # if this is present, the task manager will use a newHeads subscription to watch for new blocks
    # if not present, the task manager will use polling to get the highest block
    ws: "ws://localhost:8546"

    # The interval at which the task manager will poll the node for best block (default:"15s")
    # optional, only used if `ws` url is not specified
    poll-interval: "15s"

ethtypes:
  # Folder containing ABI JSONs
  abi-folder: ethtypes/_source
  # Path where to generate packages. Final folder represents package name
  package-path: ethtypes

# feature flags
feature:
  integrity:
    # Enable/disable the integrity checker
    enabled: true
  queuekeeper:
    enabled: true
    lag: 10
  # Enable this if the scraper should replace existing blocks instead of skipping them
  replace-blocks: false

# Control what to be logged using format "module=level,module=level"; `*` means all other modules
logging: "*=info"

metrics:
  # Port on which to serve Prometheus metrics
  port: 9909

# redis-related fields
redis:
  # URL of redis server (default:"localhost:6379")
  server: "meminero-redis:6379"

  # The name of the redis list the scraper will use for task management (default: "todo")
  list: "todo"

  password: ""

#storables
storable:
  accountERC20Transfers:
    enabled: false
  barn:
    enabled: true
    address: "0x10e138877df69Ca44Fdc68655f86c88CDe142D7F"
    notifications: true
  erc20transfers:
    enabled: true
  governance:
    enabled : true
    address : "0x4cAE362D7F227e3d306f70ce4878E245563F3069"
    notifications : false
  smartexposure:
    enabled: true
    epoolhelperaddress: ""
    epoolperipheryaddress: ""
    etokenfactoryaddress: ""
  smartyield:
    enabled: true
    notifications: true
    rewards:
      factories: "0x2e93403C675Ccb9C564edf2dC6001233d0650582,0x27FE2BFBb6be96D64Db0e741078A1f29Aa20226B,0x53a44A97cD2E9fb9d92ADe742a3C284695A4d72e"
  tokenprices:
    enabled: true
  yieldfarming:
    address: ""
    enabled: true

syncer:
  # The datasets to sync
  datasets: []
  # The network to sync
  network: "mainnet"
  # Path to sync files folder
  path: "./sync-files"
