version: '3.7'
services:
  redis:
    container_name: meminero-redis
    image: redis:6
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 0.0.0.0:6379:6379
    volumes:
      - .volumes/redis:/data
  postgres:
    container_name: meminero-postgres
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=meminero
      - POSTGRES_DB=meminero
      - POSTGRES_PASSWORD=password
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - .volumes/postgresql:/var/lib/postgresql/data
  meminero:
    container_name: meminero
    image: barnbridge/meminero:latest
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 127.0.0.1:3001:3001
      - 127.0.0.1:3000:3000
    environment:
      - PG_PASSWORD=password
    volumes:
      - .volumes/meminero:/config
